#!/usr/bin/env php
<?php

$uas = [];

$provider = simplexml_load_file(
    __DIR__ . '/vendor/sinergi/browser-detector/tests/BrowserDetector/Tests/_files/UserAgentStrings.xml'
);

foreach ($provider->strings as $string) {
    foreach ($string as $field) {
        $ua = explode("\n", $field->field[6]);
        $ua = array_map('trim', $ua);
        $ua = trim(implode(' ', $ua));

        $browser        = (string) $field->field[0];
        $browserVersion = (string) $field->field[1];

        $platform        = (string) $field->field[2];
        $platformVersion = (string) $field->field[3];

        $device = (string) $field->field[4];

        $uas[$ua] = [
            'browser' => [
                'name'    => $browser,
                'version' => $browserVersion,
            ],
            'platform' => [
                'name'    => $platform,
                'version' => $platformVersion,
            ],
            'device' => [
                'name'     => $device,
                'brand'    => null,
                'type'     => null,
                'ismobile' => null,
            ],
        ];
    }
}

// Get version from composer
$installed = json_decode(file_get_contents(__DIR__ . '/vendor/composer/installed.json'), true);

foreach ($installed as $package) {
    if ($package['name'] == 'sinergi/browser-detector') {
        $version = $package['version'];
        break;
    }
}

print json_encode([
    'tests'   => $uas,
    'version' => $version,
]);
