#!/usr/bin/env php
<?php

$tests = [];

require_once __DIR__ . '/vendor/autoload.php';

$finder = new \Symfony\Component\Finder\Finder();
$finder->files();
$finder->name('*.php');
$finder->ignoreDotFiles(true);
$finder->ignoreVCS(true);
$finder->sortByName();
$finder->ignoreUnreadableDirs();
$finder->in(__DIR__ . '/files');

foreach ($finder as $file) {
    /** @var \Symfony\Component\Finder\SplFileInfo $file */
    if (!$file->isFile() || 'json' !== $file->getExtension()) {
        continue;
    }

    $provider = include $file->getPathname();

    foreach ($provider as $ua => $properties) {
        $tests[$ua] = $properties;
    }
}

print json_encode([
    'tests' => $tests
]);
