#!/usr/bin/env php
<?php

error_reporting(E_ERROR | E_WARNING | E_PARSE);

use DeviceDetector\Parser\Device\DeviceParserAbstract;
use DeviceDetector\Parser\Client\Browser;

require_once __DIR__ . '/vendor/autoload.php';

$tests = [];

foreach (new FilesystemIterator(__DIR__ . '/vendor/woothee/woothee-testset/testsets') as $fixture) {
    $provider = Spyc::YAMLLoad($fixture->getPathname());

    foreach ($provider as $data) {
        $ua = $data['target'];
        if (!empty($ua)) {
            $expected = [
                'browser' => [
                    'name'    => isset($data['name']) ? $data['name'] : null,
                    'version' => isset($data['version']) ? $data['version'] : null,
                ],
                'platform' => [
                    'name'    => isset($data['os']) ? $data['os'] : null,
                    'version' => isset($data['os_version']) ? $data['os_version'] : null,
                ],
                'device' => [
                    'name'     => null,
                    'brand'    => null,
                    'type'     => isset($data['category']) ? $data['category'] : null,
                    'ismobile' => null,
                ]
            ];

            $tests[$ua] = $expected;
        }
    }
}

// woothee/woothee doesn't provide version information in code at all, looking to composer for the installed version
$installed = json_decode(file_get_contents(__DIR__ . '/vendor/composer/installed.json'), true);

foreach ($installed as $package) {
    if ($package['name'] == 'woothee/woothee-testset') {
        $version = $package['version'];
        break;
    }
}

print json_encode([
    'tests' => $tests,
    'version' => $version,
]);
