#!/usr/bin/env php
<?php

$agentListFile = $argv[1];

$agents = file($agentListFile, FILE_IGNORE_NEW_LINES);

$results   = [];
$parseTime = 0;

$start = microtime(true);
require __DIR__ . '/vendor/autoload.php';
$parser = new \Woothee\Classifier;
$parser->parse('Test String');
$initTime = microtime(true) - $start;

foreach ($agents as $agentString) {
    $start = microtime(true);
    $r     = $parser->parse($agentString);
    $end   = microtime(true) - $start;

    $results[] = [
        'useragent' => $agentString,
        'parsed'    => [
            'browser' => [
                'name'    => $r['name'],
                'version' => $r['version'],
            ],
            'platform' => [
                'name'    => $r['os'],
                'version' => $r['os_version'],
            ],
            'device' => [
                'name'     => null,
                'brand'    => null,
                'type'     => $r['category'],
                'ismobile' => null,
            ],
        ],
        'time' => $end,
    ];

    $parseTime += $end;
}

print json_encode([
    'results'     => $results,
    'parse_time'  => $parseTime,
    'init_time'   => $initTime,
    'memory_used' => memory_get_peak_usage(),
]);
