#!/usr/bin/env php
<?php

ini_set('memory_limit', -1);
ini_set('max_execution_time', -1);

require __DIR__ . '/vendor/autoload.php';
$parser = new \Woothee\Classifier();

$start = microtime(true);
$parser->parse('Test String');
$initTime = microtime(true) - $start;

// Get version from composer
$package = new \PackageInfo\Package('woothee/woothee');

echo json_encode([
    'init_time'   => $initTime,
    'memory_used' => memory_get_peak_usage(),
    'version'     => $package->getVersion(),
], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
