language: php
sudo: false
dist: trusty

php: 7.2

os: linux

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - check coding style
  - static code analysis

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer install --optimize-autoloader --prefer-dist --no-progress --no-interaction --no-suggest -vv
  - travis_retry yarn

script: skip

jobs:
  include:
    - stage: check coding style
      php: 7.2
      script:
        - vendor/bin/php-cs-fixer fix --dry-run -vv
        - yarn run prettier --check "**/*.js"

    - stage: static code analysis
      php: 7.2
      script:
        - vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=768M --no-progress
        - vendor/bin/psalm --show-info=false

notifications:
  email: false
