#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
cd "$parent_path"

composer update

./vendor/bin/browscap-php browscap:update --cache ./data --remote-file Full_PHP_BrowscapINI
