#!/usr/bin/env php
<?php

ini_set('memory_limit', -1);
ini_set('max_execution_time', -1);

$benchmarkPos = array_search('--benchmark', $argv);
$benchmark = false;

if ($benchmarkPos !== false) {
    $benchmark = true;
    unset($argv[$benchmarkPos]);
    $argv = array_values($argv);
}

$agentListFile = $argv[1];

$results   = [];
$parseTime = 0;

$start = microtime(true);
require_once __DIR__ . '/vendor/autoload.php';
use DeviceDetector\DeviceDetector;
use DeviceDetector\Parser\Device\DeviceParserAbstract;

$dd = new DeviceDetector('Test String');
$dd->skipBotDetection();
$dd->parse();
$initTime = microtime(true) - $start;

$file = new SplFileObject($agentListFile);
$file->setFlags(SplFileObject::DROP_NEW_LINE);

while (!$file->eof()) {
    $agentString = $file->fgets();

    if (!empty($agentString)) {
        $dd->setUserAgent($agentString);

        $start = microtime(true);
        $dd->parse();
        $end = microtime(true) - $start;

        $clientInfo = $dd->getClient();
        $osInfo     = $dd->getOs();
        $model = $dd->getModel();
        $brand = $dd->getBrandName();
        $device = $dd->getDeviceName();
        $isMobile = $dd->isMobile();

        if (!$benchmark) {
            $results[] = [
                'useragent' => $agentString,
                'parsed'    => [
                    'browser' => [
                        'name'    => isset($clientInfo['name']) ? $clientInfo['name'] : '',
                        'version' => isset($clientInfo['version']) ? $clientInfo['version'] : '',
                    ],
                    'platform' => [
                        'name'    => isset($osInfo['name']) ? $osInfo['name'] : '',
                        'version' => isset($osInfo['version']) ? $osInfo['version'] : '',
                    ],
                    'device' => [
                        'name'     => $model !== null ? $model : '',
                        'brand'    => $brand !== null ? $brand : '',
                        'type'     => $device !== null ? $device : '',
                        'ismobile' => $isMobile ? 'true' : 'false',
                    ],
                ],
                'time' => $end,
            ];
        }

        $parseTime += $end;
    }
}

$file = null;

print json_encode([
    'results'     => $results,
    'parse_time'  => $parseTime,
    'init_time'   => $initTime,
    'memory_used' => memory_get_peak_usage(),
    'version' => $dd::VERSION,
]);
