#!/usr/bin/env php
<?php

ini_set('memory_limit', -1);
ini_set('max_execution_time', -1);

$agentListFile = $argv[1];

$agents = file($agentListFile, FILE_IGNORE_NEW_LINES);

$results   = [];
$parseTime = 0;

$start = microtime(true);
require __DIR__ . '/vendor/autoload.php';
$cacheDir = __DIR__ . '/data';
\Crossjoin\Browscap\Cache\File::setCacheDirectory($cacheDir);
\Crossjoin\Browscap\Browscap::setDatasetType(\Crossjoin\Browscap\Browscap::DATASET_TYPE_LARGE);
$updater = new \Crossjoin\Browscap\Updater\None();
\Crossjoin\Browscap\Browscap::setUpdater($updater);
$browscap = new \Crossjoin\Browscap\Browscap();
$browscap->getBrowser('Test String');
$initTime = microtime(true) - $start;

foreach ($agents as $agentString) {
    $start = microtime(true);
    $r     = $browscap->getBrowser($agentString)->getData();
    $end   = microtime(true) - $start;

    $results[] = [
        'useragent' => $agentString,
        'parsed'    => [
            'browser' => [
                'name'    => $r->browser,
                'version' => $r->version,
            ],
            'platform' => [
                'name'    => $r->platform,
                'version' => $r->platform_version,
            ],
            'device' => [
                'name'     => $r->device_name,
                'brand'    => $r->device_maker,
                'type'     => $r->device_type,
                'ismobile' => $r->ismobiledevice,
            ],
        ],
        'time' => $end,
    ];

    $parseTime += $end;
}

print json_encode([
    'results'     => $results,
    'parse_time'  => $parseTime,
    'init_time'   => $initTime,
    'memory_used' => memory_get_peak_usage(),
]);
