#!/usr/bin/env php
<?php

ini_set('memory_limit', -1);
ini_set('max_execution_time', -1);

require __DIR__ . '/vendor/autoload.php';
$cacheDir = __DIR__ . '/data';
$bc       = new \BrowscapPHP\Browscap();
$adapter  = new \WurflCache\Adapter\File([\WurflCache\Adapter\File::DIR => $cacheDir]);
$bc->setCache($adapter);

$start = microtime(true);
$bc->getBrowser('Test String');
$initTime = microtime(true) - $start;

$memory = memory_get_peak_usage();

// Get version from composer
$package = new \PackageInfo\Package('browscap/browscap-php');

echo json_encode([
    'init_time'   => $initTime,
    'memory_used' => $memory,
    'version'     => $package->getVersion() . '-' . $bc->getCache()->getVersion(),
], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
