<?php
declare(strict_types = 1);

return [
    'browser' => [
        'name' => [
            'ahrefahrefsbot'      => 'ahrefsbot',
            'googlebotmobile'     => 'googlebot',
            'googlefeedburner'    => 'feedburner',
            'internetexplorer'    => 'ie',
            'jigbrowser'          => 'jigbrowserweb',
            'misccrawler'         => 'crawler',
            'mobiletranscoder'    => 'googlewirelesstranscoder',
            'naveryeti'           => 'yeti',
            'platystation4'       => 'playstation',
            'playstation3'        => 'playstation',
            'playstationportable' => 'sonypsp',
            'safarirssreader'     => 'safarirss',
            'salesforceradian6'   => 'radian6',
            'topsybutterfly'      => 'butterfly',
            'unknown'             => '',
            'softbankmobile'      => 'softbank',
            'windowsrssreader'    => 'windowsrssplatform',
        ],
        'version' => [
            'unknown' => '',
        ],
    ],
    'platform' => [
        'name' => [
            'blackberry'     => 'rimos',
            'blackberry10'   => 'rimos',
            'bsd'            => 'freebsd',
            'ipad'           => 'ios',
            'iphone'         => 'ios',
            'ipod'           => 'ios',
            'macosclassic'   => 'macppc',
            'playstation3'   => 'cellos',
            'playstation4'   => 'cellos',
            'rimos10'        => 'rimos',
            'unknown'        => '',
            'windows10'      => 'win10',
            'windows2000'    => 'win2000',
            'windows7'       => 'win7',
            'windows8'       => 'win8',
            'windows81'      => 'win81',
            'windows95'      => 'win95',
            'windows98'      => 'win98',
            'windowsce'      => 'wince',
            'windowsnt40'    => 'winnt',
            'windowsphoneos' => 'winphone',
            'windowsvista'   => 'winvista',
            'windowsxp'      => 'winxp',
        ],
        'version' => [
            'nt 10.0'    => '10.0',
            'nt 4.0'     => '4.0',
            'nt 4.10'    => '4.10',
            'nt 5.0'     => '5.0',
            'nt 5.1'     => '5.1',
            'nt 5.2 x64' => '5.2',
            'nt 5.2'     => '5.2',
            'nt 6.0 '    => '6.0',
            'nt 6.0'     => '6.0',
            'nt 6.1'     => '6.1',
            'nt 6.2'     => '6.2',
            'nt 6.3'     => '6.3',
            'nt 6.4'     => '6.4',
            'unknown'    => '',
            'xp 5.1'     => '5.1',
        ],
    ],
    'device' => [
        'type' => [
            'pc'         => 'desktop',
            'smartphone' => 'mobilephone',
            'unknown'    => '',
        ],
    ],
];
