#!/usr/bin/env php
<?php

ini_set('memory_limit', -1);
ini_set('max_execution_time', -1);

$agentListFile = $argv[1];

$agents = file($agentListFile, FILE_IGNORE_NEW_LINES);

$results   = [];
$parseTime = 0;

$start = microtime(true);
require __DIR__ . '/vendor/autoload.php';
$cacheDir               = __DIR__ . '/data';
$browscap               = new phpbrowscap\Browscap($cacheDir);
$browscap->doAutoUpdate = false;
// Initialize and include in init, but don't want to blow out the time on a real agent
// if cache loading and all that has to happen here
$browscap->getBrowser('Test String');
$initTime = microtime(true) - $start;

foreach ($agents as $agentString) {
    $start = microtime(true);
    $r     = $browscap->getBrowser($agentString);
    $end   = microtime(true) - $start;

    $results[] = [
        'useragent' => $agentString,
        'parsed'    => [
            'browser' => [
                'name'    => $r->Browser,
                'version' => $r->Version,
            ],
            'platform' => [
                'name'    => $r->Platform,
                'version' => $r->Platform_Version,
            ],
            'device' => [
                'name'     => $r->Device_Name,
                'brand'    => $r->Device_Maker,
                'type'     => $r->Device_Type,
                'ismobile' => $r->isMobileDevice ? 'true' : 'false',
            ],
        ],
        'time' => $end,
    ];

    $parseTime += $end;
}

print json_encode([
    'results'     => $results,
    'parse_time'  => $parseTime,
    'init_time'   => $initTime,
    'memory_used' => memory_get_peak_usage(),
]);
