#!/usr/bin/env php
<?php

ini_set('memory_limit', -1);
ini_set('max_execution_time', -1);

require __DIR__ . '/vendor/autoload.php';
$cacheDir               = __DIR__ . '/data';
$browscap               = new phpbrowscap\Browscap($cacheDir);
$browscap->doAutoUpdate = false;
// Initialize and include in init, but don't want to blow out the time on a real agent
// if cache loading and all that has to happen here
$start = microtime(true);
$browscap->getBrowser('Test String');
$initTime = microtime(true) - $start;

// Get version from composer
$package = new \PackageInfo\Package('browscap/browscap-php');

echo json_encode([
    'init_time'   => $initTime,
    'memory_used' => memory_get_peak_usage(),
    'version'     => $package->getVersion() . '-' . $browscap->getSourceVersion(),
], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
