#!/usr/bin/env php
<?php

$tests = [];

foreach (new FilesystemIterator(__DIR__ . '/vendor/browscap/browscap/tests/issues') as $fixture) {
    if ($fixture->getFilename() === 'issue-000-invalids.php') {
        continue;
    }
    if ($fixture->getFilename() === 'issue-000-invalid-versions.php') {
        continue;
    }

    $provider = include $fixture->getPathName();

    foreach ($provider as $testName => $data) {
        if ($data['full'] === false) {
            continue;
        }

        $ua = $data['ua'];

        if (!empty($ua)) {
            $isMobile = 'false';

            switch ($data['properties']['Device_Type']) {
                case 'Mobile Phone':
                case 'Tablet':
                case 'Console':
                case 'Digital Camera':
                case 'Ebook Reader':
                case 'Mobile Device':
                    $isMobile = 'true';
                    break;
            }

            $expected = [
                'browser' => [
                    'name'    => $data['properties']['Browser'],
                    'version' => $data['properties']['Version'],
                ],
                'platform' => [
                    'name'    => isset($data['properties']['Platform']) ? $data['properties']['Platform'] : 'unknown',
                    'version' => $data['properties']['Platform_Version'],
                ],
                'device' => [
                    'name'     => $data['properties']['Device_Name'],
                    'brand'    => $data['properties']['Device_Maker'],
                    'type'     => $data['properties']['Device_Type'],
                    'ismobile' => $isMobile,
                ]
            ];

            $tests[$ua] = $expected;
        }
    }
}

// Get version from composer
$package = new \PackageInfo\Package('browscap/browscap');

print json_encode([
    'tests'   => $tests,
    'version' => $package->getVersion(),
]);
