#!/usr/bin/env php
<?php

$tests = [];

foreach (new FilesystemIterator(__DIR__ . '/vendor/browscap/browscap/tests/fixtures/issues') as $fixture) {
    $provider = include $fixture->getPathName();

    foreach ($provider as $testName => $data) {
        $ua       = $data['ua'];
        if (!empty($ua)) {
            $expected = [
                'browser' => [
                    'name'    => $data['properties']['Browser'],
                    'version' => $data['properties']['Version'],
                ],
                'platform' => [
                    'name'    => $data['properties']['Platform'],
                    'version' => $data['properties']['Platform_Version'],
                ],
                'device' => [
                    'name'     => $data['properties']['Device_Name'],
                    'brand'    => $data['properties']['Device_Maker'],
                    'type'     => $data['properties']['Device_Type'],
                    'ismobile' => $data['properties']['isMobileDevice'] ? 'true' : 'false',
                ]
            ];

            $tests[$ua] = $expected;
        }
    }
}

// Get version from composer
$installed = json_decode(file_get_contents(__DIR__ . '/vendor/composer/installed.json'), true);

foreach ($installed as $package) {
    if ($package['name'] == 'browscap/browscap') {
        $version = $package['version'];
        break;
    }
}

print json_encode([
    'tests'   => $tests,
    'version' => $version,
]);
