#!/usr/bin/env node

var parser = require('woothee');
// Trigger a parse to force cache loading
var initStart = process.hrtime();
parser.parse('Test String');
var initTime = process.hrtime(initStart)[1] / 1000000000;

var package = require(require('path').dirname(require.resolve('woothee')) + '/../package.json');
var version = package.version;

var output = {
    'init_time': initTime,
    'memory_used': process.memoryUsage().heapUsed,
    'version': version
};

console.log(JSON.stringify(output));
