#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
cd "$parent_path"

php70 /usr/local/bin/composer install

php70 ./vendor/bin/browscap update --ini-load full --dir $parent_path/data
