#!/usr/bin/env php
<?php

ini_set('memory_limit', -1);
ini_set('max_execution_time', -1);


require __DIR__ . '/vendor/autoload.php';

$start = microtime(true);
$result   = new WhichBrowser\Parser('Test String');
$initTime = microtime(true) - $start;

$memory = memory_get_peak_usage();

// Get version from composer
$package = new \PackageInfo\Package('whichbrowser/parser');

echo json_encode([
    'init_time'   => $initTime,
    'memory_used' => $memory,
    'version'     => $package->getVersion(),
], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
