#!/usr/bin/env php
<?php

ini_set('memory_limit', -1);
ini_set('max_execution_time', -1);

$agentListFile = $argv[1];

$results   = [];
$parseTime = 0;

$start = microtime(true);
require __DIR__ . '/vendor/autoload.php';
$result   = new WhichBrowser\Parser('Test String');
$initTime = microtime(true) - $start;

$file = new SplFileObject($agentListFile);
$file->setFlags(SplFileObject::DROP_NEW_LINE);

while (!$file->eof()) {
    $agentString = $file->fgets();

    $start = microtime(true);
    $r     = new WhichBrowser\Parser($agentString);
    $end   = microtime(true) - $start;

    $results[] = [
        'useragent' => $agentString,
        'parsed'    => [
            'browser' => [
                'name'    => isset($r->browser->name) ? $r->browser->name : '',
                'version' => isset($r->browser->version) ? $r->browser->version->value : '',
            ],
            'platform' => [
                'name'    => isset($r->os->name) ? $r->os->name : '',
                'version' => isset($r->os->version) ? $r->os->version->value : '',
            ],
            'device' => [
                'name'     => isset($r->device->model) ? $r->device->model : '',
                'brand'    => isset($r->device->manufacturer) ? $r->device->manufacturer : '',
                'type'     => isset($r->device->type) ? $r->device->type : '',
                'ismobile' => $r->isMobile() ? 'true' : 'false',
            ],
        ],
        'time' => $end,
    ];

    $parseTime += $end;
}

$file = null;

print json_encode([
    'results'     => $results,
    'parse_time'  => $parseTime,
    'init_time'   => $initTime,
    'memory_used' => memory_get_peak_usage(),
]);
