#!/usr/bin/env php
<?php

ini_set('memory_limit', -1);
ini_set('max_execution_time', -1);

$agentListFile = $argv[1];

$results   = [];
$parseTime = 0;

$start = microtime(true);
require __DIR__ . '/vendor/autoload.php';
$result   = new WhichBrowser\Parser('Test String');
$initTime = microtime(true) - $start;

$file = new SplFileObject($agentListFile);
$file->setFlags(SplFileObject::DROP_NEW_LINE);

while (!$file->eof()) {
    $agentString = $file->fgets();

    if (!empty($agentString)) {
        $start = microtime(true);
        $r     = new WhichBrowser\Parser($agentString);
        $end   = microtime(true) - $start;

        $results[] = [
            'useragent' => $agentString,
            'parsed'    => [
                'browser' => [
                    'name'    => $r->browser->name !== null ? $r->browser->name : '',
                    'version' => $r->browser->version !== null ? $r->browser->version->value : '',
                ],
                'platform' => [
                    'name'    => $r->os->name !== null ? $r->os->name : '',
                    'version' => $r->os->version !== null ? $r->os->version->value : '',
                ],
                'device' => [
                    'name'     => $r->device->model !== null ? $r->device->model : '',
                    'brand'    => $r->device->manufacturer !== null ? $r->device->manufacturer : '',
                    'type'     => $r->device->type !== null ? $r->device->type : '',
                    'ismobile' => $r->isMobile() ? 'true' : 'false',
                ],
            ],
            'time' => $end,
        ];

        $parseTime += $end;
    }
}

$file = null;

print json_encode([
    'results'     => $results,
    'parse_time'  => $parseTime,
    'init_time'   => $initTime,
    'memory_used' => memory_get_peak_usage(),
]);
