#!/usr/bin/env php
<?php

ini_set('memory_limit', -1);
ini_set('max_execution_time', -1);

require __DIR__ . '/vendor/autoload.php';
$cacheDir  = __DIR__ . '/data';
$fileCache = new \Doctrine\Common\Cache\FilesystemCache($cacheDir);
$cache     = new \Roave\DoctrineSimpleCache\SimpleCacheAdapter($fileCache);
$logger    = new \Monolog\Logger('null');
$bc        = new \BrowscapPHP\Browscap($cache, $logger);

$start = microtime(true);
$bc->getBrowser('Test String');
$initTime = microtime(true) - $start;

$memory = memory_get_peak_usage();

// Get version from composer
$package = new \PackageInfo\Package('browscap/browscap-php');

$bcCache = new \BrowscapPHP\Cache\BrowscapCache($cache, $logger);

echo json_encode([
    'init_time'   => $initTime,
    'memory_used' => $memory,
    'version'     => $package->getVersion() . '-' . $bcCache->getVersion(),
], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
