#!/usr/bin/env node

var Browscap = require('browscap-js');
var browscap = new Browscap();

var start = process.hrtime();
// Trigger a parse to force cache loading
browscap.getBrowser('Test String');
var end = process.hrtime(start)[1] / 1000000000;

var browscapPackage = require(require('path').dirname(require.resolve('browscap-js')) + '/package.json');
var version = browscapPackage.version;

var output = {
    'init_time': end,
    'memory_used': process.memoryUsage().heapUsed,
    'version': version
};

console.log(JSON.stringify(output));
