#!/usr/bin/env php
<?php

$agentListFile = $argv[1];

$agents = file($agentListFile, FILE_IGNORE_NEW_LINES);

$results   = [];
$parseTime = 0;

$start = microtime(true);
require_once __DIR__ . '/vendor/autoload.php';
$browscap = new \Crossjoin\Browscap\Browscap();

$parser = new \Crossjoin\Browscap\Parser\Sqlite\Parser(__DIR__ . '/data');
$browscap->setParser($parser);
$browscap->getBrowser('Test String');
$initTime = microtime(true) - $start;

foreach ($agents as $agentString) {
    $start = microtime(true);
    $r     = $browscap->getBrowser($agentString);
    $end   = microtime(true) - $start;

    $results[] = [
        'useragent' => $agentString,
        'parsed'    => [
            'browser' => [
                'name'    => $r->browser,
                'version' => $r->version,
            ],
            'platform' => [
                'name'    => $r->platform,
                'version' => $r->platform_version,
            ],
            'device' => [
                'name'     => $r->device_name,
                'brand'    => $r->device_maker,
                'type'     => $r->device_type,
                'ismobile' => $r->ismobiledevice ? 'true' : 'false',
            ],
        ],
        'time' => $end,
    ];

    $parseTime += $end;
}

print json_encode([
    'results'     => $results,
    'parse_time'  => $parseTime,
    'init_time'   => $initTime,
    'memory_used' => memory_get_peak_usage(),
]);
